### PR TITLE
Social Media - Milestone 6: Changes to friendship relations for performance improvement

### PR DESCRIPTION
**Pull request by ldelbel**
Hello TSE,

In this milestone I changed and refactored mainly the user.rb to improve the functionality of the following methods:

- friends
- friend_requests
- pending_requests
- confirm_friend

The changes were mainly on the direction of switching from ruby functions to model queries, with the goal of improving performance.

I kindly ask for review.

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Impressive work @ldelbel :clap: However, some changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

#### Implementation (required) :warning: 
* [x] The main purpose of the controllers is to intercept user request. All logic related to DB and ActiveRecord querying should be encapsulated inside the models.
* [x] in order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables) not in **Controllers**

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
* [x] when friendship is confirmed, an additional row with reversed user-friend pair is created. You have a similar method but inside the user model. Confirming the friendship should be at the friendship model level.

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
* [x] Use **/helpers** To reduce logic from views (Loops, conditionals, queries, etc...)
* [x] Add test for the features that you implemented in this milestone.
#### N + 1 Queries (OPTIONAL)
* [ ] I Encourge you to read about `n+1` and make sure there are no `n + 1` queries in index views [Recommended article](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5).

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by ldelbel** [comment]
Hello TSE,

I didn't create new specs because I didn't actually create new features, just changed them. Most of my tests are integration tests, and they cover all the features even after refactoring.

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Well done guys :+1: :100: :clap:, you are almost there, just some couples changes :hammer: :wrench: and your milestone will be approved :heavy_check_mark:.

- [x] in the request page you have some issues on the styling  please fix them:
image

- [x] as requested by the previous TSE please remove all the logic from the view and put it in */helpers*.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

**Review by mosesogwo — APPROVED** [review]
**Hello :wave:**
**Well done :+1: You're fit to :rocket:**

### Status: Approved:heavy_check_mark:

**Pull request merged**
